=== Geonovum/xml_schematron/1.0_ow-1.0.3_op-Validatie-_en_conformiteitsregels_TPOD/business_rules/imop-businessrules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
  targetNamespace="https://standaarden.overheid.nl/stop/imop/businessrules/" version="1.0.3"
  xmlns:br="https://standaarden.overheid.nl/stop/imop/businessrules/"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- TOEKENNING VAN SCHEMA AAN INSTANCES -->
  <xs:element name="Schemata">
    <xs:annotation>
      <xs:documentation>Root-element: de lijst van schemakoppelingen aan XML-instances</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="br:versie" />
        <xs:element maxOccurs="unbounded" name="Documenttype">
          <xs:annotation>
            <xs:documentation>Documenttype (root-element) van de XML-instance 
              waarvan de validaties worden vastgelegd.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:group ref="br:mgDocumenttype" />
              <xs:element maxOccurs="1" minOccurs="1" ref="br:implementatie" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attributeGroup ref="br:agRoot" />
    </xs:complexType>
  </xs:element>

  <xs:element name="localName" type="xs:NCName">
    <xs:annotation>
      <xs:documentation>localName zonder namespace-prefix van het root-element</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="namespace" type="xs:anyURI">
    <xs:annotation>
      <xs:documentation>uitgeschreven namespace van het Root-element</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="implementatie">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="br:Schema" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Schema">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="1" ref="br:type" />
        <xs:element maxOccurs="1" minOccurs="1" ref="br:locatie" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="type" type="br:schematypes" />
  <xs:simpleType name="schematypes">
    <xs:restriction base="xs:token">
      <xs:enumeration value="schematron" />
      <xs:enumeration value="XML-schema" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="locatie" type="xs:anyURI">
    <xs:annotation>
      <xs:documentation>de volledige URL (https://standaarden.overheid.nl/...) 
        van het XML-schema/schematron</xs:documentation>
    </xs:annotation>
  </xs:element>

  <!-- SPECIFICATIE VAN BUSINESS RULES -->
  <xs:element name="BusinessRules">
    <xs:annotation>
      <xs:documentation>Root element: de container van de business rules</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="0" ref="br:versie" />
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="br:BusinessRuleGroep" />
      </xs:sequence>
      <xs:attributeGroup ref="br:agRoot" />
    </xs:complexType>
  </xs:element>

  <xs:element name="BusinessRuleGroep">
    <xs:annotation>
      <xs:documentation>groepering van business rules die voor één specifieke set van documenttypes gelden</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="0" ref="br:groepsnaam" />
        <xs:element maxOccurs="1" minOccurs="1" ref="br:id" />
        <xs:element maxOccurs="1" minOccurs="1" ref="br:geldtVoor" />
        <xs:element maxOccurs="1" minOccurs="1" ref="br:geldendeBusinessRules" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="groepsnaam" type="xs:string" />
  <xs:element name="id" type="br:idType" />

  <xs:element name="geldtVoor">
    <xs:annotation>
      <xs:documentation>de documenttypes waarop de business rules van de groep van toepassing zijn</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:choice>
        <xs:element maxOccurs="unbounded" minOccurs="1" name="Documenttype">
          <xs:complexType>
            <xs:group ref="br:mgDocumenttype" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="br:soortRegeling" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="soortRegeling" type="xs:token" />

  <xs:element name="geldendeBusinessRules">
    <xs:annotation>
      <xs:documentation>de business rules die gelden op de documenttypes van de groep</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="br:BusinessRule" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="BusinessRule">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="1" ref="br:code" />
        <xs:element maxOccurs="1" minOccurs="1" ref="br:ernst" />
        <xs:element maxOccurs="1" minOccurs="1" ref="br:regel" />
        <xs:element maxOccurs="1" minOccurs="0" ref="br:melding" />
        <xs:element maxOccurs="1" minOccurs="0" ref="br:documentatie" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="code" type="br:dtCode" />
  <xs:element name="ernst" type="br:dtErnst" />
  <xs:element name="regel" type="xs:string" />

  <xs:element name="melding">
    <xs:complexType mixed="true">
      <xs:choice>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="br:var" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="var">
    <xs:complexType>
      <xs:attribute name="naam" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="documentatie">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="br:link" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="link">
    <xs:complexType mixed="true">
      <xs:attribute name="href" type="xs:anyURI" />
    </xs:complexType>
  </xs:element>

  <!-- GENERIEK -->
  <xs:element name="versie" type="xs:token" />

  <xs:attributeGroup name="agRoot">
    <xs:attribute name="schemaversie" use="required" />
  </xs:attributeGroup>

  <xs:group name="mgDocumenttype">
    <xs:sequence>
      <xs:element maxOccurs="1" minOccurs="1" ref="br:localName" />
      <xs:element maxOccurs="1" minOccurs="1" ref="br:namespace" />
    </xs:sequence>
  </xs:group>

  <xs:simpleType name="dtErnst">
    <xs:restriction base="xs:token">
      <xs:enumeration value="fout" />
      <xs:enumeration value="waarschuwing" />
      <xs:enumeration value="informatief" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="dtCode">
    <xs:restriction base="xs:ID">
      <xs:pattern value="[A-Z]{4}[0-9]{4,5}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="idType">
    <xs:restriction base="xs:ID">
      <xs:pattern value="\c+" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== Geonovum/xml_schematron/1.0_ow-1.0.4_op-Validatie-_en_conformiteitsregels_TPOD/business_rules/BusinessRule(Groep)s_Geonovum.xml
<?xml version="1.0" encoding="UTF-8"?>
<BusinessRules schemaversie="1.0.3"
  xmlns="https://standaarden.overheid.nl/stop/imop/businessrules/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/businessrules/
  https://standaarden.overheid.nl/stop/1.0.3/imop-businessrules.xsd">
  <BusinessRuleGroep>
    <groepsnaam>AMvB/MR</groepsnaam>
    <id>BRG0001</id>
    <geldtVoor>
      <soortRegeling>/join/id/stop/regelingtype_001</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_002</soortRegeling>
    </geldtVoor>
    <geldendeBusinessRules>
      <BusinessRule>
        <code>TPOD1830</code>
        <ernst>waarschuwing</ernst>
        <regel>Binnen het object ‘Gebiedsaanwijzing’ is de waarde ‘functie’ van attribuut ‘type’ (datatype TypeGebiedsaanwijzing) niet toegestaan. (voor AMvB/MR)</regel>
        <melding>Binnen het object ‘Gebiedsaanwijzing’ in AMvB/MR is de waarde ‘Functie’ van
          attribuut ‘type’ (datatype TypeGebiedsaanwijzing) niet toegestaan. Het object waarom het
          gaat: <var naam="object-identificatie" />
        </melding>
      </BusinessRule>
      <BusinessRule>
        <code>TPOD1840</code>
        <ernst>waarschuwing</ernst>
        <regel>Binnen het object ‘Gebiedsaanwijzing’ is de waarde ‘beperkingengebied’ van attribuut ‘type’ (datatype TypeGebiedsaanwijzing) niet toegestaan. (voor AMvB/MR) </regel>
        <melding>Binnen het object ‘Gebiedsaanwijzing’ in AMvB/MR is de waarde ‘Beperkingengebied’
          van attribuut ‘type’ (datatype TypeGebiedsaanwijzing) niet toegestaan. Het object waarom
          het gaat: <var naam="object-identificatie" />
        </melding>
        <documentatie>
          <link href="TODO link naar documentatie" />
        </documentatie>
      </BusinessRule>
    </geldendeBusinessRules>
  </BusinessRuleGroep>
  <BusinessRuleGroep>
    <groepsnaam>Omgevingsplan</groepsnaam>
    <id>BRG0002</id>
    <geldtVoor>
      <soortRegeling>/join/id/stop/regelingtype_003</soortRegeling>
    </geldtVoor>
    <geldendeBusinessRules>
      <BusinessRule>
        <code>TPOD1790</code>
        <ernst>fout</ernst>
        <regel>Het IMOW-object 'Instructieregel' is niet van toepassing (voor Omgevingsplan).</regel>
        <melding>TPOD1790: Het IMOW-object 'Instructieregel' is niet van toepassing. Betreft: <var
            naam="TODO var-naam ipv XPath string(r:artikelOfLid/r:RegeltekstRef/@xlink:href)" />
        </melding>
        <documentatie>
          <link href="TODO link naar documentatie" />
        </documentatie>
      </BusinessRule>
    </geldendeBusinessRules>
  </BusinessRuleGroep>
  <BusinessRuleGroep>
    <groepsnaam>OP-implementatie-GemeentenEnWaterschappen</groepsnaam>
    <id>BRG0003</id>
    <geldtVoor>
      <soortRegeling>/join/id/stop/regelingtype_003</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_005</soortRegeling>
    </geldtVoor>
    <geldendeBusinessRules>
      <BusinessRule>
        <code>TPOD0740</code>
        <ernst>waarschuwing</ernst>
        <regel>Artikelen moeten oplopend worden genummerd in Arabische cijfers.</regel>
        <melding>TPOD_0740: Artikelnummers moeten oplopend worden genummerd in Arabische cijfers
          (betreft hoofdstuk: <var naam="TODO var-naam ipv XPath $hoofdstuk" />, artikelen: <var
            naam="TODO var-naam ipv XPath substring($volgorde, 1, string-length($volgorde) - 2)"
           />)</melding>
        <documentatie>
          <link href="TODO link naar documentatie" />
        </documentatie>
      </BusinessRule>
      <BusinessRule>
        <code>TPOD0780</code>
        <ernst>waarschuwing</ernst>
        <regel>Leden moeten per artikel oplopend genummerd worden in Arabische cijfers.</regel>
        <melding>TPOD_0780: Leden moeten per artikel oplopend genummerd worden in Arabische cijfers
          (en indien nodig, een letter). (betreft artikel: <var naam="TODO var-naam ipv XPath
            $artikel" />, leden: <var naam="TODO var-naam ipv XPath substring($volgorde, 1,
            string-length($volgorde) - 2)" />)</melding>
        <documentatie>
          <link href="TODO link naar documentatie" />
        </documentatie>
      </BusinessRule>
      <BusinessRule>
        <code>TPOD0830</code>
        <ernst>waarschuwing</ernst>
        <regel>De onderdelen van de Lijst op het eerste niveau moeten worden aangegeven met letters.</regel>
        <melding>TPOD_0830: functie, hoe doe ik dit.</melding>
        <documentatie>
          <link href="TODO link naar documentatie" />
        </documentatie>
      </BusinessRule>
      <BusinessRule>
        <code>TPOD0840</code>
        <ernst>waarschuwing</ernst>
        <regel>De onderdelen van de Lijst op het tweede niveau moeten worden aangegeven met Arabische cijfers.</regel>
        <melding>TPOD_0840: functie, hoe doe ik dit</melding>
        <documentatie>
          <link href="TODO link naar documentatie" />
        </documentatie>
      </BusinessRule>
      <BusinessRule>
        <code>TPOD0850</code>
        <ernst>waarschuwing</ernst>
        <regel>De onderdelen van de Lijst op het derde niveau moeten worden aangegeven met Arabische cijfers.</regel>
        <melding>TPOD_0850: functie, hoe doe ik dit</melding>
        <documentatie>
          <link href="TODO link naar documentatie" />
        </documentatie>
      </BusinessRule>
    </geldendeBusinessRules>
  </BusinessRuleGroep>
  <BusinessRuleGroep>
    <groepsnaam>OP-implementatie-generiek</groepsnaam>
    <id>BRG0004</id>
    <geldtVoor>
      <soortRegeling>/join/id/stop/regelingtype_001</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_002</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_003</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_004</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_005</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_006</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_007</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_008</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_009</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_010</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_011</soortRegeling>
    </geldtVoor>
    <geldendeBusinessRules>
      <BusinessRule>
        <code>TPOD0940</code>
        <ernst>fout</ernst>
        <regel>Als een Locatie uit meer dan één geometrie bestaat, dan moeten de geometrieën volgens dezelfde coordinate reference system (crs) zijn opgebouwd.</regel>
        <melding>H:TP0D940: Een geometrie moet zijn opgebouwd middels één coordinate reference
          system (crs): EPSG:28992 (=RD new) of EPSG:4258 (=ETRS89). Id=<var naam="TODO var-naam ipv
            XPath parent::*/basisgeo:id" /> bevat een combinatie van beiden. </melding>
        <documentatie>
          <link href="TODO link naar documentatie" />
        </documentatie>
      </BusinessRule>
      <BusinessRule>
        <code>TPOD1010</code>
        <ernst>waarschuwing</ernst>
        <regel>Begrippen moeten in alfabetische volgorde worden gesorteerd.</regel>
        <melding>TPOD_1010_1060: Een Begriplijst moet gesorteerd zijn, de Begrippenlijst met wId:
            "<var naam="TODO var-naam ipv XPath $items" />" is dat niet</melding>
        <documentatie>
          <link href="TODO link naar documentatie" />
        </documentatie>
      </BusinessRule>
    </geldendeBusinessRules>
  </BusinessRuleGroep>
  <BusinessRuleGroep>
    <groepsnaam>OP-implementatie-niet-Rijk</groepsnaam>
    <id>BRG0005</id>
    <geldtVoor>
      <soortRegeling>/join/id/stop/regelingtype_003</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_004</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_005</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_006</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_007</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_008</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_009</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_010</soortRegeling>
      <soortRegeling>/join/id/stop/regelingtype_011</soortRegeling>
    </geldtVoor>
    <geldendeBusinessRules>
      <BusinessRule>
        <code>TPOD0410</code>
        <ernst>waarschuwing</ernst>
        <regel>Een Hoofdstuk moet worden geduid met de label Hoofdstuk.</regel>
        <melding>TPOD_0410: Een Hoofdstuk moet worden geduid met de label Hoofdstuk. (betreft
          hoofdstuk: <var naam="TODO var-naam ipv XPath tekst:Nummer" />, label: <var naam="TODO
            var-naam ipv XPath tekst:Label" />)</melding>
        <documentatie>
          <link href="TODO link naar documentatie" />
        </documentatie>
      </BusinessRule>
      <BusinessRule>
        <code>TPOD0420</code>
        <ernst>waarschuwing</ernst>
        <regel>Hoofdstukken moeten oplopend worden genummerd in Arabische cijfers.</regel>
        <melding>TPOD_0420: Hoofdstukken moeten oplopend worden genummerd in Arabische cijfers
          (betreft hoofdstukken: <var naam="TODO var-naam ipv XPath
            substring($volgorde,1,string-length($volgorde)-2)" />)</melding>
        <documentatie>
          <link href="TODO link naar documentatie" />
        </documentatie>
      </BusinessRule>
      <BusinessRule>
        <code>TPOD0460</code>
        <ernst>waarschuwing</ernst>
        <regel>Een Titel moet worden geduid met de label Titel.</regel>
        <melding>TPOD_0460: Een Titel moet worden geduid met de label Titel. Betreft titel, label:
            <var naam="TODO var-naam ipv XPath tekst:Nummer" />:<var naam="TODO var-naam ipv XPath
            tekst:Label" />
        </melding>
        <documentatie>
          <link href="TODO link naar documentatie" />
        </documentatie>
      </BusinessRule>
      <BusinessRule>
        <code>TPOD0470</code>
